# Generated by Django 6.0.3 on 2026-05-06 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('inpatient', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('condition', models.CharField(blank=True, max_length=150)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('notes', models.TextField()),
                ('visit_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_rounds', to='patients.admissionrecord')),
                ('doctor', models.ForeignKey(limit_choices_to={'role__name': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_doctor_rounds', to=settings.AUTH_USER_MODEL)),
                ('invoice_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_rounds', to='billing.invoiceline')),
            ],
            options={
                'ordering': ['-round_time'],
            },
        ),
    ]
