# Generated by Django 6.0.3 on 2026-05-08 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0003_doctororder'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinical_cleared', models.BooleanField(default=False)),
                ('final_diagnosis', models.TextField(blank=True)),
                ('discharge_summary', models.TextField(blank=True)),
                ('treatment_given', models.TextField(blank=True)),
                ('condition_at_discharge', models.CharField(blank=True, max_length=150)),
                ('discharge_medications', models.TextField(blank=True)),
                ('follow_up_advice', models.TextField(blank=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('clinical_cleared_at', models.DateTimeField(blank=True, null=True)),
                ('nursing_cleared', models.BooleanField(default=False)),
                ('vitals_stable', models.BooleanField(default=False)),
                ('iv_removed', models.BooleanField(default=False)),
                ('catheter_removed', models.BooleanField(default=False)),
                ('instructions_explained', models.BooleanField(default=False)),
                ('nursing_notes', models.TextField(blank=True)),
                ('nursing_cleared_at', models.DateTimeField(blank=True, null=True)),
                ('billing_cleared', models.BooleanField(default=False)),
                ('generate_bed_charges', models.BooleanField(default=True)),
                ('billing_notes', models.TextField(blank=True)),
                ('billing_cleared_at', models.DateTimeField(blank=True, null=True)),
                ('pharmacy_cleared', models.BooleanField(default=False)),
                ('pharmacy_notes', models.TextField(blank=True)),
                ('pharmacy_cleared_at', models.DateTimeField(blank=True, null=True)),
                ('final_discharge_completed', models.BooleanField(default=False)),
                ('final_discharge_at', models.DateTimeField(blank=True, null=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_clearance', to='patients.admissionrecord')),
                ('billing_cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_discharge_clearances', to=settings.AUTH_USER_MODEL)),
                ('clinical_cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_discharge_clearances', to=settings.AUTH_USER_MODEL)),
                ('final_discharge_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_discharge_clearances', to=settings.AUTH_USER_MODEL)),
                ('nursing_cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_discharge_clearances', to=settings.AUTH_USER_MODEL)),
                ('pharmacy_cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_discharge_clearances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
