# Generated by Django 5.0.6 on 2024-05-21 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
        ('opd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='notes',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis',
            field=models.TextField(default='No diagnosis provided'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='opd.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='prescription',
            field=models.TextField(default='No prescription provided'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='symptoms',
            field=models.TextField(default='No symptoms provided'),
        ),
    ]
