# Generated by Django 6.0.3 on 2026-05-08 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0003_doctororder'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='source_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_order', to='inpatient.doctororder'),
        ),
    ]
