# Generated by Django 6.0.3 on 2026-05-08 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('emergency', 'Emergency')], default='external', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('referred_at', models.DateTimeField()),
                ('referred_to_facility', models.CharField(blank=True, max_length=200)),
                ('referred_to_department', models.CharField(blank=True, max_length=120)),
                ('referred_to_doctor', models.CharField(blank=True, max_length=120)),
                ('reason', models.TextField()),
                ('provisional_diagnosis', models.TextField(blank=True)),
                ('treatment_given', models.TextField(blank=True)),
                ('investigations_summary', models.TextField(blank=True)),
                ('current_condition', models.TextField(blank=True)),
                ('transport_advice', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='patients.admissionrecord')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_referrals', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='patients.patient')),
            ],
            options={
                'ordering': ['-referred_at', '-created_at'],
            },
        ),
    ]
